"""add rental period to listings

Revision ID: 4ba5061b862a
Revises: 7e7f0744adde
Create Date: 2026-06-17 16:26:10.225500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba5061b862a'
down_revision = '7e7f0744adde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_period', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_listings_fts'), postgresql_using='gin')
        batch_op.create_index('ix_listings_fts', [sa.literal_column("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,''))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_fts', postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_listings_fts'), [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
        batch_op.drop_column('rental_period')

    # ### end Alembic commands ###
