"""add wishlist table, drop trust_score from users

Revision ID: 7e7f0744adde
Revises: d97fb198338d
Create Date: 2026-06-16 12:26:23.053134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7f0744adde'
down_revision = 'd97fb198338d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_user_listing_wishlist')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_fts'), postgresql_using='gin')
        batch_op.create_index('ix_listings_fts', [sa.literal_column("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,''))")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['reg_no'])
        batch_op.drop_column('trust_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trust_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_fts', postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_listings_fts'), [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')

    op.drop_table('wishlists')
    # ### end Alembic commands ###
