"""cascade delete wishlists

Revision ID: 993403af9a64
Revises: 4ba5061b862a
Create Date: 2026-06-17 16:53:42.530367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993403af9a64'
down_revision = '4ba5061b862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_fts'), postgresql_using='gin')
        batch_op.create_index('ix_listings_fts', [sa.literal_column("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,''))")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('wishlists_listing_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wishlists_listing_id_fkey'), 'listings', ['listing_id'], ['id'])

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_fts', postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_listings_fts'), [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
