"""Add reg_no to User model

Revision ID: d97fb198338d
Revises: d9e7ce106530
Create Date: 2026-06-13 10:02:47.782666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97fb198338d'
down_revision = 'd9e7ce106530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_fts'), postgresql_using='gin')
        batch_op.create_index('ix_listings_fts', [sa.literal_column("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,''))")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reg_no')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_fts', postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_listings_fts'), [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
